set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports demod]
set_property IOSTANDARD LVCMOS33 [get_ports feed_ground]
set_property IOSTANDARD LVCMOS33 [get_ports feed_signal]
set_property IOSTANDARD LVCMOS33 [get_ports switch_ground]
set_property IOSTANDARD LVCMOS33 [get_ports switch_pwm]
set_property PACKAGE_PIN R2 [get_ports clk]
set_property PACKAGE_PIN A15 [get_ports feed_ground]

set_property IOSTANDARD LVCMOS33 [get_ports switch_signal]

set_property PACKAGE_PIN U15 [get_ports switch_pwm]
set_property PACKAGE_PIN V16 [get_ports demod]

set_property IOSTANDARD LVCMOS33 [get_ports busy]
set_property IOSTANDARD LVCMOS33 [get_ports sw_0]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property PACKAGE_PIN E15 [get_ports busy]
set_property PACKAGE_PIN B13 [get_ports feed_signal]
set_property PACKAGE_PIN H14 [get_ports sw_0]
set_property PACKAGE_PIN R12 [get_ports uart_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN E18 [get_ports {LED[0]}]
set_property PACKAGE_PIN F13 [get_ports {LED[1]}]
set_property PACKAGE_PIN E13 [get_ports {LED[2]}]
set_property PACKAGE_PIN H15 [get_ports {LED[3]}]
